"""empty message

Revision ID: 02e068f01bd8
Revises: c25c28e3fb7b
Create Date: 2023-05-26 14:46:39.641237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02e068f01bd8'
down_revision = 'c25c28e3fb7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('followee_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'user', ['followee_id'], ['id'])
    op.drop_column('followers', 'followed_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('followed_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'user', ['followed_id'], ['id'])
    op.drop_column('followers', 'followee_id')
    # ### end Alembic commands ###
